### ISSUE TITLE
encoder不能动态尺寸推理

### ISSUE THREAD

**Issue by limaopeng1** [SWHL/ConvertLaTeXOCRToONNX#1]
请问encoder只能固定尺寸推理吗，我使用动态尺寸推理会出现如下错误：
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 49 by 57

**Comment by limaopeng1** [comment]
> 可以展开说一下你怎么使用动态尺寸推理的吗？我没太明白

我改了下推理代码，输入图片的预处理没有使用image_resizer.onnx，而是直接在原图片上padding到32的倍数，所以我的输出图片的尺寸是不固定的，可能是32*320、32*480、48*320等

现在问题encoder.onnx好像不支持改变输入图像的尺寸，但是在转onnx模型的时候设置了动态推理 dynamic_axes，理论上应该是可以支持不同输入图像的尺寸的

torch.onnx.export(
                self.encoder,
                x,
                save_onnx_path,
                export_params=True,
                opset_version=11,
                verbose=False,
                input_names=["input"],
                output_names=["output"],
                do_constant_folding=True,
                dynamic_axes={
                    "input": {0: "batch", 2: "height", 3: "width"},
                    "output": {0: "batch", 1: "context1", 2: "context2"},
                },
            )

**Comment by limaopeng1** [comment]
> 明白了，可以尝试用onnx对encoder.onnx做一下更改。类似下面这样：
> 
> ```python
> import onnx
> 
> model_path = 'encoder.onnx'
> onnx_model = onnx.load(model_path)
> 
> onnx_model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = 'None' 
> 
> # 修改NCHW中H为动态输入
> onnx_model.graph.input[0].type.tensor_type.shape.dim[2].dim_param = '?' 
> 
> # 修改NCHW中W为动态输入，同理可设置N、C为动态输入
> onnx_model.graph.input[0].type.tensor_type.shape.dim[3].dim_param = '?' 
> 
> onnx.save(onnx_model, model_path)
> ```

这个还是不能解决问题

**Comment by SWHL** [comment]
我想你那里肯定有问题。我测试了用image_resizer情况下，输入到encoder.onnx前图像是支持动态的。
测试代码如下：
```python
from pathlib import Path
from rapid_latex_ocr import LatexOCR

model = LatexOCR()

img_list = Path('tests/test_files').glob('*.png')
for img_path in img_list:
    res, elapse = model(img_path)

    print(res)
    print(elapse)
```

打印进入encoder前图像的shape:
在[这行](https://github.com/RapidAI/RapidLaTeXOCR/blob/ce264231de2257201f407b67e767d9950742ffb1/rapid_latex_ocr/main.py#L102)添加打印代码：


输出结果如下：
```bash
$ python demo.py 
(1, 1, 64, 192)
x={\frac{-b\pm{\sqrt{b^{2}-4a c\ }}}{2a}}
0.2774650000000001
(1, 1, 64, 128)
{\frac{x^{2}}{a^{2}}}-{\frac{y^{2}}{b^{2}}}=1
0.2778508339999999
(1, 1, 32, 96)
x^{2}+y^{2}=1
0.085934167
(1, 1, 64, 352)
\exp\left[\in
```

**Comment by breezedeus** [comment]
感谢作者的工作。我也遇到了同样的问题。encoder、decoder 转 onnx 没问题，但是使用时只能用相同宽度的图片才行，估计是 dynamic_axes没有真正生效。求一下作者的 Python 的版本以及安装包的详细列表🙏：
```bash
$ python --version
$ pip freeze
```

**Comment by SWHL** [comment]
我试了一下我这里新转出的onnx模型，发现在推理时也不行了。报错如下：
```bash
(1, 1, 32, 160)
进入encoder部分
Traceback (most recent call last):
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/utils_load.py", line 51, in __call__
    return self.session.run(None, input_dict)
  File "/Users/xxxx/opt/miniconda3/envs/convert_latex_ocr/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 13 by 21


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/main.py", line 111, in __call__
    dec = self.encoder_decoder(resizered_img, temperature=self.temperature)
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/models.py", line 31, in __call__
    context = self.encoder([x])[0]
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/utils_load.py", line 54, in __call__
    raise ONNXRuntimeError(error_info) from e
rapid_latex_ocr.utils_load.ONNXRuntimeError: Traceback (most recent call last):
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/utils_load.py", line 51, in __call__
    return self.session.run(None, input_dict)
  File "/Users/xxxx/opt/miniconda3/envs/convert_latex_ocr/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 13 by 21



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxxx/projects/RapidLatexOCR/demo.py", line 12, in <module>
    res, elapse = model(data)
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/main.py", line 114, in __call__
    raise ValueError(
ValueError: EncoderDecoder meets error. Error info is Traceback (most recent call last):
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/utils_load.py", line 51, in __call__
    return self.session.run(None, input_dict)
  File "/Users/xxxx/opt/miniconda3/envs/convert_latex_ocr/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 13 by 21


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/main.py", line 111, in __call__
    dec = self.encoder_decoder(resizered_img, temperature=self.temperature)
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/models.py", line 31, in __call__
    context = self.encoder([x])[0]
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/utils_load.py", line 54, in __call__
    raise ONNXRuntimeError(error_info) from e
rapid_latex_ocr.utils_load.ONNXRuntimeError: Traceback (most recent call last):
  File "/Users/xxxx/projects/RapidLatexOCR/rapid_latex_ocr/utils_load.py", line 51, in __call__
    return self.session.run(None, input_dict)
  File "/Users/xxxx/opt/miniconda3/envs/convert_latex_ocr/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 13 by 21
```

我再看看，你们有遇到过吗？

**Comment by SWHL** [comment]
不能推理的问题已经解决了。请以上各位拉取最新代码重新尝试一下吧！

**Comment by SWHL** [comment]
issue先关闭了哈，有问题再开

**Comment by Zalways** [comment]
> 不能动态推理的问题已经解决了。请以上各位拉取最新代码重新尝试一下吧！

请问您是怎么解决这个动态推理的问题的呢？我也遇到了类似的问题，我的代码在python环境下没导出onnx时可以支持动态输入推理，但是导出的onnx之后，使用onnx进行推理的话就只能支持固定尺寸了，否则就报错，报错信息与您之前的不支持动态尺寸的报错一样   感谢回复  Thanks♪(･ω･)ﾉ！

**Comment by SWHL** [comment]
@Zalways 问题比较综合，有很多地方。建议去参考我的commit来看看吧，我也说不太清。

**Comment by Zalways** [comment]
> @Zalways 问题比较综合，有很多地方。建议去参考我的commit来看看吧，我也说不太清。

感谢回复！ 我的模型是一个基于Deformable-detr的端到端文字识别模型，也是在encoder做注意力的节点报错不支持多尺度，就像请问一下大体的修改方向是哪一块
